### ISSUE TITLE
ORDS pod creation issue

### ISSUE THREAD

**Issue by ocimbaluria** [oracle/oracle-database-operator#52] opened 2023-03-20 06:50 UTC
Hello,

I had an issue with the creation of an ORDS pod on top of a database pod, both created using the operator.
After a successful database creation, I used the standard provided yaml fil to create the ORDS pod but whereas the service was created, the pod wasn't.
ORDS pod creation logs :
2023-03-16T17:44:23Z	INFO	controllers.OracleRestDataService	Found Existing Service 	{"createSVC": "default/ordsmg", "Service.Name": "ordsmg"}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	No ordsmg Pod is Ready 	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg"}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	ordsmg Pods Available ( Other Than Ready Pod )	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg", " Names :": []}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	Total No Of ordsmg PODS	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg", "Count": 0}
2023-03-16T17:44:23Z	INFO	controllers.OracleRestDataService	PVC already exists	{"createPVC": "default/ordsmg"}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	Ready Pod 	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg", "Name :": "sidb-db-r7dm4"}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	sidb-mongodb Pods Available ( Other Than Ready Pod )	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg", " Names :": []}
2023-03-16T17:44:23Z	INFO	controller.oraclerestdataservice	Total No Of sidb-mongodb PODS	{"reconciler group": "database.oracle.com", "reconciler kind": "OracleRestDataService", "name": "ordsmg", "namespace": "default", "FindPods": "default/ordsmg", "Count": 1}
2023-03-16T17:44:23Z	DEBUG	events	Normal	{"object": {"kind":"OracleRestDataService","namespace":"default","name":"ordsmg","uid":"128a8010-4434-451b-a27f-a22b2975a5f2","apiVersion":"database.oracle.com/v1alpha1","resourceVersion":"60095605"}, "reason": "Database Check", "message": "status of database sidb-db is ready"}
2023-03-16T17:44:23Z	INFO	controllers.OracleRestDataService	Reconcile queued

Logs where cycling in the reconcile queue.

Operator version : 0.2.1
Database Version : 21.3
ORDS version : 21.21.4.2-gh

**Comment by cimbaklm** [comment] 2023-03-20 06:51
Hi,
The issue was the structure of the ords password, their was an ending $. After removing the ending $, ORDS pod creation was successful.

**Comment by Rajas-B** [comment] 2023-04-03 05:09
Hi,
I am curious as to how you were able to attach the connection string required to run ORDS. I get this error whenever I try to apply its yaml file
`INFO : This container will start a service running ORDS 22.4.4 and APEX 22.2.0. ERROR: CONN_STRING_FILE has not added, create a file with CONN_STRING variable and added as docker volume: mkdir volume ; echo 'CONN_STRING=user/password@hostname:port/service_name' > volume/conn_string.txt`

**Comment by yunus-qureshi** [comment] 2023-04-03 05:49
@Rajas-B which ORDS image are you using?

**Comment by Rajas-B** [comment] 2023-04-03 06:21
I was using ORDS 22.4.4. I realized now that it supports up to 22.2.1. But I am still confused as to how I will provide the connection string to the ORDS container.

**Comment by yunus-qureshi** [comment] 2023-04-03 06:29
Which controller are you trying here and which tutorial are you referring to?

**Comment by Rajas-B** [comment] 2023-04-03 06:43
I am following the [multitenant model tutorial](https://github.com/oracle/oracle-database-operator/blob/main/docs/multitenant/README.md). I have an Oracle database running to which I am trying to connect to through the ORDS image to manage the PDBs.

**Comment by yunus-qureshi** [comment] 2023-04-03 07:10
yes, that needs you to build the image as documented. The one in container-registry will not work

**Comment by vatsrahul** [comment] 2023-05-15 09:02
> Hi,
> The issue was the structure of the ords password, their was an ending. ORDS pod creation was successful.
@ocimbaluria  What was the password ending which was giving you this issue ?
I am not able to reproduce this issue.

**Comment by ocimbaluria** [comment] 2023-05-15 09:07
Hi @vatsrahul,
For my case, the issue was linked to an ending $ in my password

**Comment by vatsrahul** [comment] 2023-08-10 11:33
This issue was addressed in 1.0.0

**Closed** 2023-08-10 12:04 UTC
